plugins {
    id 'com.android.application'
}

android {
    namespace 'com.luizcalori.horadoalmoco'
    compileSdk 35

    defaultConfig {
        applicationId "com.luizcalori.horadoalmoco"
        minSdk 26
        targetSdk 35
        versionCode 13
        versionName "2.1.4"
    }

    buildTypes {
        debug {
            debuggable false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
